### ISSUE TITLE
EADDRINUSE trying to debug 

### ISSUE THREAD

**Issue by korsmakolnikov** [avajs/ava#1010]
## Description
I've seen an old issue like this you say was resolved by node updates. In my case not. I'm try to debug ava test with webstorm and phpstorm and got this:

### Error Message & Stack Trace
![image](https://cloud.githubusercontent.com/assets/13141364/17768649/3f2e2dc4-6535-11e6-9335-a8974ef3d382.png)

### Config
From package.json:
`"ava": "^0.16.0",`

Config to run
![image](https://cloud.githubusercontent.com/assets/13141364/17768679/5eec31d8-6535-11e6-97d0-408b8ded5cab.png)

**Node version is 6.3.1** on ubuntu 15.10

### Command-Line Arguments
`/usr/bin/node --debug-brk=45516 --nolazy cli.js --verbose ../../tests/testDataTableComposer.js`

I can't figure out a way to force the port number of cli. But is strange: even if the port number is random cli can't find any that wasn't busy...

**Comment by sindresorhus** [comment]
It's fixed in master (https://github.com/avajs/ava/commit/c268c8dfce325010f84dd4097ba8696c5f3a47c1) and will be available in the next release: https://github.com/avajs/ava/blob/master/docs/recipes/debugging-with-webstorm.md

**Comment by jasongin** [comment]
I'm trying to debug using VS Code. I got the fix above to resolve the EADDRINUSE issue. But now the problem is the debugger only attaches to the parent process, so the 4 child processes sit waiting forever for a debugger that never attaches.

```
node --debug-brk=15326 --nolazy node_modules\ava\cli.js --serial --verbose build/test/*.js 
Debugger listening on port 15326
Debugger listening on port 2027
Debugger listening on port 2028
Debugger listening on port 2029
Debugger listening on port 2030
```

Why does ava launch 4 child processes, even when the --serial flag is passed? I think to successfully debug it would need to run the tests directly in the main process.

**Comment by sindresorhus** [comment]
@jasongin I think that fix is only for WebStorm. For a CLI fix, see https://github.com/avajs/ava/pull/929.

**Comment by korsmakolnikov** [comment]
@jasongin still having this issue in phpstorm. Doesn't share same enging with webstorm?
